# markcheck bash completion. Generated by tools/build_docs.py.
_markcheck() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  case "$prev" in
    --only|--exclude)
      COMPREPLY=( $(compgen -W "zero-width invisible-format bidi variation-selector tag whitespace default-ignorable" -- "$cur") ); return ;;
    --min-severity)
      COMPREPLY=( $(compgen -W "info low medium high" -- "$cur") ); return ;;
    --max-bytes|--max-hits|--show)
      return ;;
  esac
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--exclude --force --help --in-place --include-default-ignorables --json --list-categories --max-bytes --max-hits --min-severity --no-backup --only --show --stdout --strip --suspicious-only --version -h" -- "$cur") )
  else
    COMPREPLY=( $(compgen -f -- "$cur") )
  fi
}
complete -F _markcheck markcheck
