#compdef markcheck
# markcheck zsh completion. Generated by tools/build_docs.py.
_arguments -s \
  '-h[show this help message and exit]' \
  '--help[show this help message and exit]' \
  '--strip[write a cleaned copy (FILE.clean.EXT) with hits removed]' \
  '--in-place[with --strip, overwrite the original (writes a .bak backup unless --no]' \
  '--no-backup[with --in-place, skip the .bak backup]' \
  '--stdout[with --strip on stdin, write cleaned text to stdout]' \
  '--json[emit JSON]' \
  '--force[with --strip, overwrite an existing FILE.clean.EXT]' \
  '--only[comma-separated categories to scan (e.g. zero-width,bidi)]:category:(zero-width invisible-format bidi variation-selector tag whitespace default-ignorable)' \
  '--exclude[comma-separated categories to skip]:category:(zero-width invisible-format bidi variation-selector tag whitespace default-ignorable)' \
  '--min-severity[report only hits at or above LEVEL (info, low, medium, high; default i]:severity:(info low medium high)' \
  '--suspicious-only[shorthand for --min-severity medium: drop the annotated, likely-legiti]' \
  '--include-default-ignorables[also scan every remaining Unicode default-ignorable code point (noisy;]' \
  '--max-bytes[refuse inputs larger than N bytes (default 104857600; 0 = unlimited)]:value:' \
  '--max-hits[cap stored hit records at N to bound memory (default 200000; 0 = unlim]:value:' \
  '--show[max locations to list (default 20)]:value:' \
  '--list-categories[print the taxonomy and exit]' \
  '--version[show programs version number and exit]' \
  '*:file:_files'
