#!/usr/bin/env python3
"""Generate the man page and shell completions from markcheck.py.

Like the browser build, these are generated rather than hand-maintained: the
option list comes straight from the argparse parser, so a new flag cannot ship
with a stale man page or a completion that does not know about it. CI
regenerates and diffs, so drift fails the build.

Usage: python3 tools/build_docs.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

import markcheck as m  # noqa: E402

# Static because the man page date must not change on every rebuild; bump it
# with the release.
MAN_DATE = "2026-08-14"


def options(parser):
    """Yield (joined_flags, metavar, help) for every optional argument."""
    for action in parser._actions:
        if not action.option_strings:
            continue
        metavar = ""
        if action.nargs != 0 and action.metavar:
            metavar = " " + action.metavar
        elif action.nargs != 0 and action.choices:
            metavar = " {" + ",".join(str(c) for c in action.choices) + "}"
        yield ", ".join(action.option_strings), metavar, action.help or ""


def roff_escape(text):
    # A leading dot or apostrophe starts a roff request; backslash escapes.
    return text.replace("\\", "\\e").replace("-", "\\-")


def man_page(parser):
    out = [
        f'.TH MARKCHECK 1 "{MAN_DATE}" "markcheck {m.__version__}" '
        f'"User Commands"',
        ".SH NAME",
        "markcheck \\- scan text for hidden and invisible Unicode characters",
        ".SH SYNOPSIS",
        ".B markcheck",
        "[\\fIOPTION\\fR]... [\\fIFILE\\fR]...",
        ".SH DESCRIPTION",
        roff_escape(
            "Detects zero-width characters, bidirectional controls, variation "
            "selectors, nonstandard whitespace, invisible format code points, "
            "and the Unicode Tags block: code points that render as nothing, "
            "or as an ordinary-looking space, yet occupy distinct bytes. With "
            "no FILE, or when FILE is -, read standard input."),
        ".PP",
        roff_escape(
            "markcheck inspects the byte stream, so it finds marks that ARE "
            "bytes. It does not detect statistical (token-distribution) "
            "watermarks, and it does not read C2PA provenance metadata."),
        ".SH OPTIONS",
    ]
    for flags, metavar, helptext in options(parser):
        out.append(".TP")
        out.append(f"\\fB{roff_escape(flags)}\\fR{roff_escape(metavar)}")
        out.append(roff_escape(helptext))
    out.append(".SH EXIT STATUS")
    for code, meaning in ((0, "no hidden characters were found"),
                          (1, "hidden characters were found"),
                          (2, "usage error, or a read or write failed"),
                          (130, "interrupted"),
                          (141, "terminated by SIGPIPE (POSIX)")):
        out.append(".TP")
        out.append(f".B {code}")
        out.append(roff_escape(meaning))
    out.append(".SH CATEGORIES")
    for name, desc in m.CATEGORIES.items():
        out.append(".TP")
        out.append(f"\\fB{roff_escape(name)}\\fR")
        out.append(roff_escape(desc))
    out.append(".SH SEVERITY")
    out.append(roff_escape(
        "Each hit is rated " + ", ".join(m.SEVERITIES) + ". Annotated, "
        "likely-legitimate hits are info. Use --min-severity or "
        "--suspicious-only to narrow scope; the exit code and --strip follow "
        "the same scope."))
    out.append(".SH SEE ALSO")
    out.append(roff_escape("c2patool(1), exiftool(1)"))
    out.append(".SH AUTHOR")
    out.append("MavProDev.")
    return "\n".join(out) + "\n"


def bash_completion(parser):
    flags = " ".join(sorted(
        f for a in parser._actions for f in a.option_strings))
    cats = " ".join(m.CATEGORIES)
    sevs = " ".join(m.SEVERITIES)
    return f"""# markcheck bash completion. Generated by tools/build_docs.py.
_markcheck() {{
  local cur prev
  cur="${{COMP_WORDS[COMP_CWORD]}}"
  prev="${{COMP_WORDS[COMP_CWORD-1]}}"
  case "$prev" in
    --only|--exclude)
      COMPREPLY=( $(compgen -W "{cats}" -- "$cur") ); return ;;
    --min-severity)
      COMPREPLY=( $(compgen -W "{sevs}" -- "$cur") ); return ;;
    --max-bytes|--max-hits|--show)
      return ;;
  esac
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "{flags}" -- "$cur") )
  else
    COMPREPLY=( $(compgen -f -- "$cur") )
  fi
}}
complete -F _markcheck markcheck
"""


def zsh_completion(parser):
    lines = []
    for flags, metavar, helptext in options(parser):
        desc = helptext.replace("'", "").replace("[", "(").replace("]", ")")
        desc = " ".join(desc.split())[:70]
        for flag in flags.split(", "):
            if flag == "--only" or flag == "--exclude":
                arg = ":category:(" + " ".join(m.CATEGORIES) + ")"
            elif flag == "--min-severity":
                arg = ":severity:(" + " ".join(m.SEVERITIES) + ")"
            elif metavar:
                arg = ":value:"
            else:
                arg = ""
            lines.append(f"  '{flag}[{desc}]{arg}' \\")
    body = "\n".join(lines)
    return f"""#compdef markcheck
# markcheck zsh completion. Generated by tools/build_docs.py.
_arguments -s \\
{body}
  '*:file:_files'
"""


def build():
    parser = m.build_parser()
    written = []
    targets = (
        (os.path.join(ROOT, "docs", "markcheck.1"), man_page(parser)),
        (os.path.join(ROOT, "completions", "markcheck.bash"),
         bash_completion(parser)),
        (os.path.join(ROOT, "completions", "markcheck.zsh"),
         zsh_completion(parser)),
    )
    for path, content in targets:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
        written.append((path, len(content)))
    return written


if __name__ == "__main__":
    for path, size in build():
        print(f"wrote {path} ({size} bytes)")
